### PR TITLE
Fix some bugs and improve the performance for searching references.

### PR DESCRIPTION
**Pull request by Gh0u1L5**
Knock knock, this PR
* Fixed some small typos I made in parser.ts,
* Handle file create/rename/change events in a more robust way,
* And improved the logic about renaming and searching references.

I've tested the fixes a little while, it goes well, so I guess that's it, have fun. (｡ •̀ ᴗ - )✧

### CODE REVIEW

**Comment by Gh0u1L5** [comment]
Ah, one more thing. So in this PR, to allow fast reference searching, I made the extension load all the smali files into the memory. Which apparently will cause a dramatic increase in memory usage.

I guess this may not be a big deal. Since the main vscode program already takes 150~200MB memory without any extensions, it should be okay for our extension to use, well, <100MB memory? But probably we should add a configurable switch, to allow user to enable/disable such memory-consuming features?

**Comment by LoyieKing** [comment]
> Ah, one more thing. So in this PR, to allow fast reference searching, I made the extension load all the smali files into the memory. Which apparently will cause a dramatic increase in memory usage.
> 
> I guess this may not be a big deal. Since the main vscode program already takes 150~200MB memory without any extensions, it should be okay for our extension to use, well, <100MB memory? But probably we should add a configurable switch, to allow user to enable/disable such memory-consuming features?

_(:3」∠❀)_I wonder that won't be a great solution. In fact,a smali project larger than 200MB is quit common, and due to the limitations of javascript, it is almost impossible to write a fast and low memory footprint vscode extension.
Well,  I actually thought about this problem some time ago. My idea at the time was to use C# to rewrite this extension, which can reduce a lot of memory usage and increase the speed  (and it will even be able to add a smali simulate function and more). But soon as my schoolwork got busy(mole), I put these plans on hold. 
So... Maybe we can rewrite the project later using a more native lang?

**Comment by Gh0u1L5** [comment]
Sure, sounds good to me. However, instead of using C#, I'm thinking about using some other languages that are more lightweight, e.g. Rust or Go? So that we can box the whole thing in a docker to support other systems like Linux/Mac?

**Comment by surendrajat** [comment]
@LoyieKing we can leverage the language server idea that's is already implemented for most of the languages.
@Gh0u1L5 +1 for Go. If you start this I will also be able to contribute. Performance is also very comparable to that of rust.

**Pull request merged**
